# Generated by Django 5.0 on 2025-11-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_rename_redirect_url_toolconfig_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='viva_duration_seconds',
            field=models.IntegerField(default=600),
        ),
    ]
