# Generated by Django 5.0 on 2025-11-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_assignment_viva_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instructor_notes',
            field=models.TextField(blank=True, help_text='Private instructor notes about the assignment or viva. Not visible to students.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric_text',
            field=models.TextField(blank=True, help_text='Optional marking rubric (never shown to students — used for instructor review and AI summaries).'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='viva_instructions',
            field=models.TextField(blank=True, help_text="Guidance for how the AI should conduct the viva (tone, focus, probing depth, do/don't)."),
        ),
    ]
