# Generated by Django 5.0 on 2025-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_assignment_instructor_notes_assignment_rubric_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='rubric_text',
        ),
        migrations.AddField(
            model_name='assignment',
            name='arrhythmic_typing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='event_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='keystroke_tracking',
            field=models.BooleanField(default=True),
        ),
    ]
