# Generated by Django 5.0 on 2025-11-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_remove_assignment_rubric_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VivaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('misconceptions', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.vivasession')),
            ],
        ),
    ]
