# Generated by Django 5.0 on 2025-12-30 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0035_userprofile_terms_acceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ai_feedback_visible',
            field=models.BooleanField(default=True, help_text='Allow students to see AI feedback.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='feedback_released_at',
            field=models.DateTimeField(blank=True, help_text='Legacy AI feedback release timestamp.', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='feedback_visibility',
            field=models.CharField(default='immediate', help_text='Legacy AI feedback visibility flag.', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher_feedback_visible',
            field=models.BooleanField(default=True, help_text='Allow students to see teacher feedback.'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentmembership',
            unique_together={('assignment', 'user', 'role')},
        ),
    ]
