# Generated by Codex on 2026-01-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0044_merge_20260109_0803"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="mcq_enabled",
            field=models.BooleanField(default=False, help_text="Enable an MCQ round before the viva chat."),
        ),
        migrations.AddField(
            model_name="assignment",
            name="mcq_question_count",
            field=models.PositiveSmallIntegerField(default=0, help_text="Number of MCQ questions to ask at the start of the viva."),
        ),
        migrations.AddField(
            model_name="vivasession",
            name="mcq_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vivasession",
            name="mcq_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vivasession",
            name="mcq_total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VivaSessionMcqQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("question", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_index", models.PositiveSmallIntegerField(default=0)),
                ("student_index", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mcq_questions", to="tool.vivasession")),
            ],
        ),
    ]
