# Generated by Codex on 2026-01-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0045_assignment_mcq_fields_and_session_mcq"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="mcq_only",
            field=models.BooleanField(default=False, help_text="Run MCQ only and auto-submit after the quiz."),
        ),
    ]
